@startuml
node and_1
node and_2
node google_recaptcha
node smart_contract_whitelist
node single_address_call_limit

and_1 --[#green]> result:true
single_address_call_limit --[#green]> and_1:true
and_2 --[#green]> and_1:true
google_recaptcha --[#green]> and_2:true
smart_contract_whitelist --[#green]> and_2:true
@enduml