@startuml
left to right direction
frame exchange{
card cold_wallet
card hot_wallet
card asset_management_service
card privete_DaaS
}

frame public_server1{
    card faucet_new_DApp
    card vote_DApp
    card public_DaaS_1
}

frame public_server2{
    card NFT_DApp
    card DEX_DApp
    card Game_DApp
    card public_DaaS_2
}

card VechainThor_Blockchain as chain

hot_wallet <-> cold_wallet:transfer token
hot_wallet <-- asset_management_service
cold_wallet <-- asset_management_service
asset_management_service <-- privete_DaaS:agent to pay VTHO

faucet_new_DApp <-- public_DaaS_1:agent to pay VTHO
vote_DApp <-- public_DaaS_1

NFT_DApp <-- public_DaaS_2:agent to pay VTHO
DEX_DApp <-- public_DaaS_2
Game_DApp <-- public_DaaS_2


privete_DaaS -- chain
public_DaaS_1 -- chain
public_DaaS_2 -- chain
@enduml